default:
  before_script:
    - docker info

stages:
  - build
  - push
  - update-tag

variables:
  DOCKER_BUILDKIT: "1"
  IMAGE_NAME: "aspirely.marketing-website"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  FULL_IMAGE: "$HARBOR_URL/$HARBOR_PROJECT/$IMAGE_NAME:$IMAGE_TAG"

build:
  stage: build
  tags:
    - aspirely
  script:
    - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --progress=plain -t $FULL_IMAGE .

push:
  stage: push
  tags:
    - aspirely
  script:
    - echo "$HARBOR_PASSWORD" | docker login "$HARBOR_URL" -u "$HARBOR_USER" --password-stdin
    - docker push $FULL_IMAGE

update-tag:
  stage: update-tag
  script:
    - git clone https://oauth2:$GITOPS_ACCESS_TOKEN@gitlab.aspirely.edu.vn/aspirely/gitops.git
    - cd gitops/apps/aspirely.marketing-website
    - 'sed -i "s|image: .*aspirely.marketing-website:.*|image: $FULL_IMAGE|" deployment.yaml'
    - git config user.email "ci@gitlab.com"
    - git config user.name "GitLab CI"
    - git add deployment.yaml
    - 'git commit -m "ci: update image tag to $CI_COMMIT_SHORT_SHA"'
    - git push
  only:
    - main