apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspirely-marketing-website
  labels:
    app: aspirely-marketing-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspirely-marketing-website
  template:
    metadata:
      labels:
        app: aspirely-marketing-website
    spec:
      containers:
        - name: aspirely-marketing-website
          image: 127.0.0.1:5000/aspirely-marketing:latest
          ports:
            - containerPort: 3000
