FROM node:18-alpine

WORKDIR /app
COPY . .

ARG GOOGLE_SHEET_ID
ARG GOOGLE_SERVICE_EMAIL
ARG GOOGLE_PRIVATE_KEY
ARG RESEND_API_KEY

ENV GOOGLE_SHEET_ID=$GOOGLE_SHEET_ID
ENV GOOGLE_SERVICE_EMAIL=$GOOGLE_SERVICE_EMAIL
ENV GOOGLE_PRIVATE_KEY=$GOOGLE_PRIVATE_KEY
ENV RESEND_API_KEY=$RESEND_API_KEY

RUN npm install
RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
