name: Build, Push, Deploy Aspirely Marketing Website

on: [push, pull_request]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to self-hosted registry
        run: echo ${{ secrets.REGISTRY_PASS }} | docker login 23.88.120.37:5000 -u ${{ secrets.REGISTRY_USER }} --password-stdin

      - name: Build and push image
        run: |
          docker build -t 23.88.120.37:5000/aspirely-marketing-website:${GITHUB_SHA} .
          docker push 23.88.120.37:5000/aspirely-marketing-website:${GITHUB_SHA}

      - name: Update deployment.yaml image tag
        run: |
          sed -i "s|image: .*|image: registry.local:5000/aspirely-marketing-website:${GITHUB_SHA}|g" /opt/infrastructures/aspirely-marketing-website-deployment/deployment.yaml

      - name: Deploy to k3s
        run: kubectl apply -f /opt/infrastructures/aspirely-marketing-website-deployment/
