apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspirely-marketing-website
  labels:
    app: aspirely-marketing-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspirely-marketing-website
  template:
    metadata:
      labels:
        app: aspirely-marketing-website
    spec:
      containers:
        - name: aspirely-marketing-website
          image: registry.aspirely.edu.vn/aspirely-marketing:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: aspirely-marketing-website-env
          imagePullPolicy: Always
          imagePullSecrets:
          - name: aspirely-registry-secret
