name: develop

on:
  push:
    branches:
      - develop

env:
  IMAGE_NAME: "aspirely.marketing-website.staging"
  HARBOR_URL: ${{ secrets.HARBOR_URL }}
  HARBOR_PROJECT: ${{ secrets.HARBOR_PROJECT }}
  HARBOR_USER: ${{ secrets.HARBOR_USER }}
  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
  GITOPS_ACCESS_TOKEN: ${{ secrets.GITOPS_ACCESS_TOKEN }}

jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Set FULL_IMAGE
        run: echo "FULL_IMAGE=${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/${IMAGE_NAME}:${SHORT_SHA}" >> $GITHUB_ENV
      - name: Docker login
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login "${{ secrets.HARBOR_URL }}" -u "${{ secrets.HARBOR_USER }}" --password-stdin
      - name: Docker build
        run: docker build -t "$FULL_IMAGE" .
      - name: Docker push
        run: docker push "$FULL_IMAGE"

  update-tag:
    runs-on: self-hosted
    needs: build_and_push
    steps:
      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Set FULL_IMAGE
        run: echo "FULL_IMAGE=${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/${IMAGE_NAME}:${SHORT_SHA}" >> $GITHUB_ENV
      - name: Update GitOps repo
        run: |
          git clone https://oauth2:${{ secrets.GITOPS_ACCESS_TOKEN }}@github.com/AspirelyVN/gitops.git
          cd gitops/apps/aspirely.marketing-website.staging
          sed -i "s|image: .*aspirely.marketing-website.staging:.*|image: $FULL_IMAGE|" deployment.yaml
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          if ! git diff --quiet deployment.yaml; then
            git add deployment.yaml
            git commit -m "ci: update staging image tag to $SHORT_SHA"
            git push
          fi
